### ISSUE TITLE
Format of signatures embedded in scripts/executables

### ISSUE THREAD

**Issue by ita1024** [tedu/reop#21]
Since a new non-standard signature format is chosen, how about making one safe for signed scripts/executables? For example, python scripts can be both signed and be executable, but lines starting with "---" are syntax errors.
Signatures starting with # characters will pose no problem in shell, python, ruby and perl:
#REOP#signature contents(\r)\n<EOF>

The same thing can be applied to regular executables/binary files as well, assuming 8-bit data (iso8859-1?) it may be possible to embed a signature at the end of the file.

**Comment by tedu** [comment]
Interesting idea, but I think it's getting too specific and I'm not sure the use cases really justify it.

Is the script part of a package with documentation, etc.? Then the entirety of the tgz should be signed, not just the script.

Is it a one off script? Distribute it as a signed message. If it's important enough that people should verify it before using, they should use reop to "extract" it.
